spring:
  datasource:
#    url:  jdbc:postgresql://localhost:5432/mynewdb
      url:  jdbc:postgresql://localhost:5432/mynewdb
      username: myuser
      password: 2381012
      driver-class-name: org.postgresql.Driver
jpa:
  hibernate:
    ddl-auto: update
